# Generated by Django 5.0.2 on 2024-02-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Imagenes/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
