# Generated by Django 5.0.2 on 2024-02-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arrendatario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('valor_cobro', models.IntegerField()),
                ('fecha_cobro', models.DateField(max_length=20)),
                ('inicio_contrato', models.DateField(max_length=20)),
                ('fin_contrato', models.DateField(max_length=20)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('obs', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'arrendatario',
            },
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('descuento', models.IntegerField()),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('habilitar', models.IntegerField()),
            ],
            options={
                'db_table': 'superuser',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('propie_client', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ref', models.CharField(max_length=10)),
                ('tipo', models.IntegerField()),
                ('valor_seguro', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
                ('habilitada', models.CharField(max_length=3)),
                ('arrendatario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.arrendatario')),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.documentos')),
            ],
            options={
                'db_table': 'propiedad',
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='propiedad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.propiedad'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='propiedad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.propiedad'),
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('valor_pago', models.IntegerField()),
                ('fecha_pago', models.DateField(max_length=20)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('obs', models.CharField(max_length=400)),
                ('propiedad_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.propiedad')),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.usuarios')),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.propietario'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.usuarios'),
        ),
    ]
