# Generated by Django 5.0.3 on 2024-05-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='descuento',
        ),
        migrations.CreateModel(
            name='Docdescuentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.IntegerField()),
                ('descrip', models.CharField(max_length=400)),
                ('documento', models.CharField(max_length=600)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Docdescuento', to='generar.inmueble')),
            ],
            options={
                'db_table': 'Docdescuentos',
            },
        ),
    ]
