# Generated by Django 5.0.2 on 2024-03-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
