# Generated by Django 5.0.2 on 2024-05-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0003_inmueble_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmueble', to='generar.arrendatario'),
        ),
    ]
