# Generated by Django 5.0.2 on 2024-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0003_alter_superuser_documento_alter_superuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_documento',
            field=models.CharField(default='Cedula', max_length=100),
            preserve_default=False,
        ),
    ]
