# Generated by Django 5.0.3 on 2024-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0004_alter_inmueble_arrendatario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='inicio',
            field=models.DateField(auto_now_add=True, default="1111-11-11"),
            preserve_default=False,
        ),
    ]
