# Generated by Django 5.0.3 on 2024-03-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0004_superuser_email_usuarios_tipo_documento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='propiedad',
            new_name='inmueble',
        ),
        migrations.AlterModelTable(
            name='inmueble',
            table='inmueble',
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descrip', models.CharField(max_length=400)),
                ('estado', models.CharField(max_length=3)),
                ('fecha_inicio', models.DateField(max_length=20)),
                ('fecha_fin', models.DateField(max_length=20)),
                ('etiqueta', models.CharField(max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('superuser_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generar.superuser')),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
    ]
