# Generated by Django 5.0.2 on 2024-05-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0005_arrendatario_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendatario',
            name='habilitarPago',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inmueble', to='generar.arrendatario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='habilitarPago',
            field=models.IntegerField(default=4),
        ),
    ]
