# Generated by Django 5.0.3 on 2024-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0005_rename_propiedad_inmueble_alter_inmueble_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
