# Generated by Django 5.0.2 on 2024-05-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0006_alter_arrendatario_habilitarpago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendatario',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrendatario', to='generar.usuarios'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propietario', to='generar.usuarios'),
        ),
    ]
