# Generated by Django 5.0.3 on 2024-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0006_alter_tareas_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='etiqueta',
            field=models.CharField(max_length=100),
        ),
    ]
