# Generated by Django 5.0.3 on 2024-03-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0007_alter_tareas_estado_alter_tareas_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='habilitar',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='habilitar',
            field=models.IntegerField(default=1),
        ),
    ]
