# Generated by Django 5.0.3 on 2024-03-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0008_usuarios_habilitar_alter_superuser_habilitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='habilitarPago',
            field=models.IntegerField(default=2),
        ),
    ]
