# Generated by Django 5.0.2 on 2024-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0008_alter_inmueble_propietario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='habilitarPago',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='estadoPago',
            field=models.IntegerField(default=4),
        ),
    ]
