# Generated by Django 5.0.2 on 2024-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0009_remove_arrendatario_habilitarpago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='habilitarPago',
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='habilitarPago',
            field=models.IntegerField(default=4),
        ),
    ]
