# Generated by Django 5.0.3 on 2024-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0009_propietario_habilitarpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='habilitarPago',
            field=models.IntegerField(default=2),
        ),
    ]
