# Generated by Django 5.0.3 on 2024-04-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0011_documentos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='documento_id',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
