# Generated by Django 5.0.2 on 2024-07-06 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0011_inmueble_fechapago_propietario_num_banco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrendatario',
            old_name='inicio',
            new_name='registro',
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='anual',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
