# Generated by Django 5.0.3 on 2024-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0012_remove_inmueble_documento_id_inmueble_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
