# Generated by Django 5.0.2 on 2024-07-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0012_rename_inicio_arrendatario_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspersonas',
            name='arrendatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocsPersona', to='generar.arrendatario'),
        ),
        migrations.AlterField(
            model_name='docspersonas',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocsPersona', to='generar.propietario'),
        ),
    ]
