# Generated by Django 5.0.3 on 2024-04-29 15:44

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0013_alter_tareas_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='fecha_inicio_cobro',
            field=models.DateField(default=datetime.date.today, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='servicios',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='bancos',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email2',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email3',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='expedida',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
