# Generated by Django 5.0.2 on 2024-08-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0013_alter_docspersonas_arrendatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('factura_arr', models.IntegerField(default=1)),
                ('factura_pro', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Consecutivo',
            },
        ),
    ]
