# Generated by Django 5.0.2 on 2024-09-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0014_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdescuentos',
            name='fecha',
            field=models.DateField(default='2024-01-01', max_length=500),
            preserve_default=False,
        ),
    ]
