# Generated by Django 5.0.2 on 2024-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0015_rename_fecha_cobro_arrendatario_fecha_fin_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
