# Generated by Django 5.0.3 on 2024-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0016_superuser_last_login'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='superuser',
            name='last_login',
        ),
    ]
