# Generated by Django 5.0.2 on 2024-05-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0017_rename_valor_inmueble_canon_and_more'),
    ]

    operations = [

    ]
