# Generated by Django 5.0.2 on 2024-05-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0018_rename_fecha_cobro_arrendatario_fecha_fin_cobro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='pdf',
            new_name='documento',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='propiedad_id',
        ),
        migrations.AddField(
            model_name='documentos',
            name='inmueble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='generar.inmueble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='descuento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='documentos',
            table='Documentos',
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='generar.inmueble')),
            ],
            options={
                'db_table': 'Imagenes',
            },
        ),
    ]
