# Generated by Django 5.0.2 on 2024-05-08 08:43

import generar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0019_rename_pdf_documentos_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='documento',
            field=models.FileField(upload_to=generar.models.carpetas_inmuebles),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(upload_to=generar.models.carpetas_inmuebles),
        ),
    ]
