# Generated by Django 5.0.3 on 2024-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar', '0020_alter_documentos_documento_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='propiedad_id',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='valor_cobro',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='propiedad_id',
        ),
    ]
